# -*- coding: utf-8 -*-
"""Video_Frames_Extraction_OpenCV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QrmPhIDaDXrgiHJeKQTolHliOCjwovmg

# Frames Extraction
- importing Libs
- Loading Video to Collab
- Reading Video in OpenCV
- Capturing Frames in OpenCV
- Storing Frames via OpenCV
"""

#lib importing
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
import os

"""## Loading Video to Collab from Drive

### Mounting File to read from Drive
"""

from google.colab import drive
drive.mount('/gdrive')

Path_VideoFile='/gdrive/My Drive/Machine-Learning-Computer-Vision/Frames-Captures-OpenCV/'
with open(Path_VideoFile +'london_Streets.mp4' , 'r+') as video_f:
  if video_f is None:
    print("Video Empty")
  else:
    print("File Access Successful! -Not Null")

"""### Reading video Frame by frame via OpenCV"""

# folder= "TestImages" # os.mkdir(folder) # cv2.imwrite(os.path.join(folder,"frame{:d}.jpg".format(count)), image)

from google.colab.patches import cv2_imshow as imshow
#capturing
cap= cv.VideoCapture(Path_VideoFile +'london_Streets.mp4')
#reading frames till video not ends
counter=1

while ( cap.isOpened() ):
  response, img_frame = cap.read() #reads frame by frame
  if response == False:
    break

  print("Frame Reading...." + str(counter) )  
  colored_Frame= cv.cvtColor(img_frame, cv.COLOR_BGR2RGB) #Overriding BGR and converting to RGB
  # imshow(colored_Frame) #displaying RGB frames
  if counter%3==0:
    cv.imwrite(Path_VideoFile+'\\london_Streets_frames_' + str(counter)+'.jpeg', colored_Frame) #Writing to File as JPEG
    print("Written Successfuly... "+ str(counter))
  counter+=1

cap.release()
cv.destroyAllWindows()

